# syntax=docker/dockerfile:1
#see https://stackoverflow.com/questions/58018300/using-a-pip-cache-directory-in-docker-builds
FROM python:3.12-bookworm as builder

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libssl3 \
    git

RUN git clone https://github.com/comfyanonymous/ComfyUI /home/comfyuser/ComfyUI
COPY extra_model_paths.serverless.yaml /home/comfyuser/ComfyUI/extra_model_paths.yaml

RUN git clone https://github.com/Fannovel16/comfyui_controlnet_aux /home/comfyuser/ComfyUI/custom_nodes/comfyui_controlnet_aux
RUN cd /home/comfyuser/ComfyUI/custom_nodes/comfyui_controlnet_aux && git checkout 7c4f6fb6ff18aa6dbfd4f77c2e8ad46119b5d84d

RUN git clone https://github.com/SamTyurenkov/ComfyUI-Inpaint-CropAndStitch /home/comfyuser/ComfyUI/custom_nodes/comfyui-inpaint-cropandstitch

ADD entry.serverless-inpaint.sh /usr/local/bin/entrypoint.sh
ADD handler.py /home/comfyuser/handler.py
ADD test_input.min.json /home/comfyuser/test_input.json
ADD .config/Ultralytics/settings.json /root/.config/Ultralytics/settings.json

WORKDIR /home/comfyuser/
RUN ["chmod", "+x", "/usr/local/bin/entrypoint.sh"]
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
