name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: samtyurenkov
          password: ${{ secrets.SAM_DOCKERHUB }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46

      - name: Set changed flags
        id: flags
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          # Initialize flags
          nginx=false
          comfyui=false
          runpod=false
          cuda_volume_runner_129=true

          # Loop through all changed files
          IFS=' ' read -r -a files <<< "$CHANGED_FILES"
          for file in "${files[@]}"; do
            [[ "$file" == docker/nginx/* ]] && nginx=true
            [[ "$file" == docker/comfyui/* ]] && comfyui=true
            [[ "$file" == docker/runpod/* ]] && runpod=true
            [[ "$file" == docker/cuda_volume_runner_129/* ]] && cuda_volume_runner_129=true
          done

          echo "nginx_changed=$nginx" >> $GITHUB_OUTPUT
          echo "comfyui_changed=$comfyui" >> $GITHUB_OUTPUT
          echo "runpod_changed=$runpod" >> $GITHUB_OUTPUT
          echo "cuda_volume_runner_129_changed=$cuda_volume_runner_129" >> $GITHUB_OUTPUT

      - name: Build and push Nginx Image
        if: steps.flags.outputs.nginx_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/nginx
          file: ./docker/nginx/Dockerfile
          push: true
          tags: samtyurenkov/nginx-comfyui:latest

      - name: Build and push Comfyui image
        if: steps.flags.outputs.comfyui_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/comfyui
          file: ./docker/comfyui/Dockerfile
          push: true
          tags: samtyurenkov/comfyui:latest

      - name: Build and push Runpod Image
        if: steps.flags.outputs.runpod_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/runpod
          file: ./docker/runpod/Dockerfile
          push: true
          tags: samtyurenkov/runpod:latest

      - name: Build and push CUDA volume runner Image
        if: steps.flags.outputs.cuda_volume_runner_129_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/cuda_volume_runner_129_changed
          file: ./docker/cuda_volume_runner_129_changed/Dockerfile
          push: true
          tags: samtyurenkov/cuda_volume_runner_129_changed:latest
