name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: samtyurenkov
          password: ${{ secrets.SAM_DOCKERHUB }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46

      - name: Set changed flags
        id: flags
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          # Initialize flags
          runpod=false
          runpod_trainer=false
          runpod_musubi_tuner=false

          # Loop through all changed files
          IFS=' ' read -r -a files <<< "$CHANGED_FILES"
          for file in "${files[@]}"; do
            [[ "$file" == docker/runpod/* ]] && runpod=true
            [[ "$file" == docker/runpod-trainer/* ]] && runpod_trainer=true
            [[ "$file" == docker/runpod-musubi-tuner/* ]] && runpod_musubi_tuner=true
          done

          echo "runpod_changed=$runpod" >> $GITHUB_OUTPUT
          echo "runpod_trainer_changed=$runpod_trainer" >> $GITHUB_OUTPUT
          echo "runpod_musubi_changed=$runpod_musubi_tuner" >> $GITHUB_OUTPUT

      - name: Build and push Runpod Image
        if: steps.flags.outputs.runpod_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/runpod
          file: ./docker/runpod/Dockerfile
          push: true
          tags: samtyurenkov/runpod:latest

      - name: Build and push Runpod Trainer Image
        if: steps.flags.outputs.runpod_trainer_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/runpod-trainer
          file: ./docker/runpod-trainer/Dockerfile
          push: true
          tags: samtyurenkov/runpod:trainer
      
      - name: Build and push Runpod Musubi Tuner Image
        if: steps.flags.outputs.runpod_musubi_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/runpod-musubi-tuner
          file: ./docker/runpod-musubi-tuner/Dockerfile
          push: true
          tags: samtyurenkov/runpod:musubi-tuner

      - name: Build and push Serverless Runpod Image
        if: steps.flags.outputs.runpod_changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./docker/runpod
          file: ./docker/runpod/Dockerfile.serverless
          push: true
          tags: samtyurenkov/runpod-serverless:v1.0
