name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: samtyurenkov
          password: ${{ secrets.SAM_DOCKERHUB }}

      - name: Get all changed nginx files
        id: changed-nginx-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            docker/nginx/**

      - name: Get all changed comfyui files
        id: changed-comfyui-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            docker/comfyui/**

      - name: Get all changed comfyui files
        id: changed-runpod-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            docker/runpod/**

      - name: Build and push Nginx Image
        if: steps.flags.changed-nginx-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/nginx
          file: ./docker/nginx/Dockerfile
          push: true
          tags: samtyurenkov/nginx-comfyui:latest

      - name: Build and push Comfyui image
        if: steps.flags.changed-comfyui-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/comfyui
          file: ./docker/comfyui/Dockerfile
          push: true
          tags: samtyurenkov/comfyui:latest

      - name: Build and push Runpod Image
        if: steps.flags.changed-runpod-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/runpod
          file: ./docker/runpod/Dockerfile
          push: true
          tags: samtyurenkov/runpod:latest
