name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: samtyurenkov
          password: ${{ secrets.SAM_DOCKERHUB }}

      - name: Get changed files
        run: echo "All changed files: ${{ toJson(github.event.head_commit.modified) }}"

      - name: Set changed flags
        id: flags
        run: |
          # Get list of modified files from GitHub event
          IFS=' ' read -r -a modified_files <<< "${{ join(github.event.head_commit.modified, ' ') }}"

          nginx=false
          comfyui=false
          runpod=false

          for file in "${modified_files[@]}"; do
            if [[ "$file" == docker/nginx/* ]]; then
              nginx=true
            elif [[ "$file" == docker/comfyui/* ]]; then
              comfyui=true
            elif [[ "$file" == docker/runpod/* ]]; then
              runpod=true
            fi
          done

          echo "nginx_changed=$nginx" >> $GITHUB_OUTPUT
          echo "comfyui_changed=$comfyui" >> $GITHUB_OUTPUT
          echo "runpod_changed=$runpod" >> $GITHUB_OUTPUT

      - name: Build and push Nginx Image
        if: steps.flags.outputs.nginx_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/nginx
          file: ./docker/nginx/Dockerfile
          push: true
          tags: samtyurenkov/nginx-comfyui:latest

      - name: Build and push Comfyui image
        if: steps.flags.outputs.comfyui_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/comfyui
          file: ./docker/comfyui/Dockerfile
          push: true
          tags: samtyurenkov/comfyui:latest

      - name: Build and push Runpod Image
        if: steps.flags.outputs.runpod_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/runpod
          file: ./docker/runpod/Dockerfile
          push: true
          tags: samtyurenkov/runpod:latest
