name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: samtyurenkov
          password: ${{ secrets.SAM_DOCKERHUB }}

      - name: Get changed files
        id: changed
        uses: dorny/actions-changed-files@v1
        with:
          files: |
            docker/nginx/**
            docker/comfyui/**
            docker/runpod/**

      - name: Set changed flags
        id: flags
        run: |
          echo "nginx=$(echo ${{ steps.changed.outputs.files }} | grep -q 'docker/nginx/' && echo 'true' || echo 'false')"
          echo "comfyui=$(echo ${{ steps.changed.outputs.files }} | grep -q 'docker/comfyui/' && echo 'true' || echo 'false')"
          echo "runpod=$(echo ${{ steps.changed.outputs.files }} | grep -q 'docker/runpod/' && echo 'true' || echo 'false')"
          echo "nginx_changed=$nginx" >> $GITHUB_OUTPUT
          echo "comfyui_changed=$comfyui" >> $GITHUB_OUTPUT
          echo "runpod_changed=$runpod" >> $GITHUB_OUTPUT

      - name: Build and push Nginx Image
        if: steps.flags.outputs.nginx_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/nginx
          file: ./docker/nginx/Dockerfile
          push: true
          tags: samtyurenkov/nginx-comfyui:latest

      - name: Build and push Comfyui image
        if: steps.flags.outputs.comfyui_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/comfyui
          file: ./docker/comfyui/Dockerfile
          push: true
          tags: samtyurenkov/comfyui:latest

      - name: Build and push Runpod Image
        if: steps.flags.outputs.runpod_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/runpod
          file: ./docker/runpod/Dockerfile
          push: true
          tags: samtyurenkov/runpod:latest
