name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: samtyurenkov
          password: ${{ secrets.SAM_DOCKERHUB }}
        
      - name: Set up Docker Buildx
        uses: useblacksmith/build-push-action@v1.1
        with:
          setup-only: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/comfyui
          file: ./docker/comfyui/Dockerfile
          push: true
          tags: samtyurenkov/comfyui:latest

      - name: Build and push Service API
        uses: docker/build-push-action@v5
        with:
          context: ./docker/nginx
          file: ./docker/nginx/Dockerfile
          push: true
          tags: samtyurenkov/nginx-comfyui:latest
