name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: samtyurenkov
          password: ${{ secrets.SAM_DOCKERHUB }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46

      - name: Set changed flags
        id: flags
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          # Initialize flags
          runpod=false
          videogen=false
          runpod_trainer=false
          runpod_musubi_tuner=false
          serverless_faceswap=false
          serverless_wd14=false
          serverless_inpaint=false
          serverless_wan2_2_i2v=false

          # Loop through all changed files
          IFS=' ' read -r -a files <<< "$CHANGED_FILES"
          for file in "${files[@]}"; do
            [[ "$file" == docker/runpod/Dockerfile ]] && runpod=true
            [[ "$file" == docker/runpod/Dockerfile.videogen ]] && videogen=true
            [[ "$file" == docker/runpod/Dockerfile.serverless-faceswap ]] && serverless_faceswap=true
            [[ "$file" == docker/runpod/Dockerfile.serverless-wd14 ]] && serverless_wd14=true
            [[ "$file" == docker/runpod/Dockerfile.serverless-inpaint ]] && serverless_inpaint=true
            [[ "$file" == docker/runpod/Dockerfile.serverless-wan2-2-i2v ]] && serverless_wan2_2_i2v=true
            [[ "$file" == docker/runpod-trainer/* ]] && runpod_trainer=true
            [[ "$file" == docker/runpod-musubi-tuner/* ]] && runpod_musubi_tuner=true
          done

          echo "runpod_changed=$runpod" >> $GITHUB_OUTPUT
          echo "videogen_changed=$videogen" >> $GITHUB_OUTPUT
          echo "serverless_faceswap_changed=$serverless_faceswap" >> $GITHUB_OUTPUT
          echo "serverless_wd14_changed=$serverless_wd14" >> $GITHUB_OUTPUT
          echo "serverless_inpaint_changed=$serverless_inpaint" >> $GITHUB_OUTPUT
          echo "serverless_wan2_2_i2v_changed=$serverless_wan2_2_i2v" >> $GITHUB_OUTPUT
          echo "runpod_trainer_changed=$runpod_trainer" >> $GITHUB_OUTPUT
          echo "runpod_musubi_changed=$runpod_musubi_tuner" >> $GITHUB_OUTPUT

      - name: Build and push Runpod Image
        if: steps.flags.outputs.runpod_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/runpod
          file: ./docker/runpod/Dockerfile
          push: true
          tags: samtyurenkov/runpod:latest

      - name: Build and push Runpod Videogen Image
        if: steps.flags.outputs.videogen_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/runpod
          file: ./docker/runpod/Dockerfile.videogen
          push: true
          tags: samtyurenkov/runpod:videogen

      - name: Build and push Runpod Trainer Image
        if: steps.flags.outputs.runpod_trainer_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/runpod-trainer
          file: ./docker/runpod-trainer/Dockerfile
          push: true
          tags: samtyurenkov/runpod:trainer
      
      - name: Build and push Runpod Musubi Tuner Image
        if: steps.flags.outputs.runpod_musubi_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./docker/runpod-musubi-tuner
          file: ./docker/runpod-musubi-tuner/Dockerfile
          push: true
          tags: samtyurenkov/runpod:musubi-tuner

      - name: Build and push Serverless Faceswap Runpod Image
        if: steps.flags.outputs.serverless_faceswap_changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./docker/runpod
          file: ./docker/runpod/Dockerfile.serverless-faceswap
          push: true
          tags: samtyurenkov/runpod-serverless-faceswap:v3.1

      - name: Build and push Serverless WD14 Runpod Image
        if: steps.flags.outputs.serverless_wd14_changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./docker/runpod
          file: ./docker/runpod/Dockerfile.serverless-wd14
          push: true
          tags: samtyurenkov/runpod-serverless-wd14:v3.1

      - name: Build and push Serverless Inpaint Runpod Image
        if: steps.flags.outputs.serverless_inpaint_changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./docker/runpod
          file: ./docker/runpod/Dockerfile.serverless-inpaint
          push: true
          tags: samtyurenkov/runpod-serverless-inpaint:v3.1

      - name: Build and push Serverless Wan2.2I2V Runpod Image
        if: steps.flags.outputs.serverless_wan2_2_i2v_changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./docker/runpod
          file: ./docker/runpod/Dockerfile.serverless-wan2-2-i2v
          push: true
          tags: samtyurenkov/runpod-serverless-wan2-2-i2v:v3.1
